load_data:
  data_path: D:\\madness_data\data
  init_elo_params: [0.3896076731384477, 6.51988202753904, 34.11927604457895, 0.17251109126016217]
  init_season: 2003
  save_path: D:\\madness_data\data  # This should usually be the same as the data_path
  save_files: False
  run_elo_opt: False

dataloader:
  datapath: D:\\madness_data\data
  train_batch_size: 32
  val_batch_size: 32
  split: .7
  single_example: False
  pin_memory: False

model:
  name: Predictor
  init_size: 70
  latent_size: 25
  sigma: 1.
  encode_sz: 5
  lr: .00001
  weight_decay: 0.4
  scheduler_gamma: .99
  betas: [.9, .99]
  num_samples: 100
  training:
    log_dir: ./logs
    swa_start: .7
    max_epochs: 100
    log_epoch: 50
    weights_path: ./models
    warm_start: False
    save_model: True
    patience: 5

encoder:
  name: Encoder
  init_size: 128
  latent_size: 70
  lr: .01
  weight_decay: 0.2
  scheduler_gamma: .99
  betas: [.9, .99]
  num_samples: 100
  run_train: False
  training:
    log_dir: ./logs
    swa_start: .7
    max_epochs: 600
    log_epoch: 50
    weights_path: ./models
    warm_start: False
    save_model: True
    patience: 50

seq_predictor:
  name: GamePredictor
  init_size: 70
  latent_size: 45
  in_channels: 5
  sigma: 1.
  encode_sz: 5
  lr: .00001
  weight_decay: 0.05
  scheduler_gamma: .99
  betas: [.9, .99]
  num_samples: 100
  training:
    log_dir: ./logs
    swa_start: .7
    max_epochs: 100
    log_epoch: 50
    weights_path: ./models
    warm_start: False
    save_model: True
    patience: 5